HER-18 - Member's message has been removed and bot's name has been added in config's file
HermesBotApp/CommunityEvent pull request #2
Opened 2022-03-28 07:56 UTC by antoinelrk

2022-03-28 11:59 UTC, Grimille requested changes
Je vois que tu ajoutes des configs, mais il faut aussi ajouter le config.yml dans les ressources pour que Hermes copie les valeurs par défaut

2022-03-28 11:59 UTC, Grimille commented on src/main/java/fr/blueberry/studio/hermes/listeners/discord/MessageReceivedListener.java
> +        event.getMessage().delete().queue();
Utilise un consumer sur la queue pour envoyer le message. Ça fluidifiera les problèmes de double message en attendant que la queue soit traitée

2022-03-28 11:59 UTC, Grimille commented on src/main/java/fr/blueberry/studio/hermes/listeners/discord/MessageReceivedListener.java
> +        event.getMessage().delete().queue();
Example: https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/RestAction.html#queue(java.util.function.Consumer)

2022-03-29 09:22 UTC, antoinelrk commented on src/main/java/fr/blueberry/studio/hermes/listeners/discord/MessageReceivedListener.java
> +        event.getMessage().delete().queue();
J'ai modifié

2022-03-29 13:58 UTC, Grimille approved these changes

2022-03-29 14:24 UTC, kiwodd commented
C'est bon, j'ai résolu le conflit avec la release/1.0

2022-03-29 16:23 UTC, Grimille approved these changes

2022-03-29 16:23 UTC, merged